//
//  RepositoriesInteractor.swift
//  StarsOfGithub
//
//  Created by Willian Pinho on 21/11/19.
//  Copyright (c) 2019 Willian Pinho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RepositoriesBusinessLogic {
    func fetchRepositories(request: Repositories.Fetch.Request)
}

protocol RepositoriesDataStore {
    var repositories: [Repository]? { get set }
}

class RepositoriesInteractor: RepositoriesBusinessLogic, RepositoriesDataStore {
    
    var presenter: RepositoriesPresentationLogic?
    var worker: RepositoriesWorker?
    var repositories: [Repository]?
    
    // MARK: Fetch
    
    func fetchRepositories(request: Repositories.Fetch.Request) {
        
//        #if DEBUG
//        self.worker = RepositoriesWorker(repositoriesStore: RepositoriesMemoryAPI())
//        #else
//        self.worker = RepositoriesWorker(repositoriesStore: RepositoriesAPI())
//        #endif
        self.worker = RepositoriesWorker(repositoriesStore: RepositoriesAPI())

    
        self.worker?.fetchRepositories(completionHandler: { (repositories) in
            self.repositories = repositories
            let response = Repositories.Fetch.Response(repositories: repositories)
            self.presenter?.presentRepositories(response: response)
        })
    }
    
}
