//
//  RepositoriesMemoryAPI.swift
//  StarsOfGithub
//
//  Created by Willian Pinho on 21/11/19.
//  Copyright (c) 2019 Willian Pinho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class RepositoriesMemoryAPI: RepositoriesStoreProtocol {
    
    static var objects = [
        Repository(title: "Title 1", subtitle: "Subtitle 1"),
        Repository(title: "Title 2", subtitle: "Subtitle 2")
    ]
    
    func fetchRepositories(completionHandler: @escaping (() throws -> [Repository]) -> Void) {
        completionHandler { return type(of: self).objects }
    }
    
}
