//
//  RepositoriesPresenter.swift
//  StarsOfGithub
//
//  Created by Willian Pinho on 21/11/19.
//  Copyright (c) 2019 Willian Pinho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RepositoriesPresentationLogic {
    func presentRepositories(response: Repositories.Fetch.Response)
}

class RepositoriesPresenter: RepositoriesPresentationLogic {
    
    weak var viewController: RepositoriesDisplayLogic?
    
    // MARK: Present Repositories
    
    func presentRepositories(response: Repositories.Fetch.Response) {
        var repositories: [Repositories.Fetch.ViewModel.Repository] = []
        
        for object in response.repositories {
            let display = Repositories.Fetch.ViewModel.Repository(
                title: object.title,
                subtitle: object.title
            )
            repositories.append(display)
        }
        
        let viewModel = Repositories.Fetch.ViewModel(repositories: repositories)
        self.viewController?.displayRepositories(viewModel: viewModel)
    }
    
}
