//
//  RepositoriesRouter.swift
//  StarsOfGithub
//
//  Created by Willian Pinho on 21/11/19.
//  Copyright (c) 2019 Willian Pinho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol RepositoriesRoutingLogic {
    //func routeToSomewhere()
}

protocol RepositoriesDataPassing {
    var dataStore: RepositoriesDataStore? { get }
}

class RepositoriesRouter: NSObject, RepositoriesRoutingLogic, RepositoriesDataPassing {
    
    weak var viewController: RepositoriesViewController?
    var dataStore: RepositoriesDataStore?
  
    // MARK: Routing
    
    //func routeToSomewhere() {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //}
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: RepositoriesViewController,
    //                         destination: SomewhereViewController) {
    //    source.show(destination, sender: nil)
    //}
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: RepositoriesDataStore,
    //                         destination: inout SomewhereDataStore) {
    //    destination.name = source.name
    //}
    
}
